apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - ../base

configMapGenerator:

  - name: aws-load-balancer-controller-values
    files:
      - values.yaml=./aws-load-balancer-controller/values.yaml
    namespace: aws-load-balancer-controller

configurations:
  - kustomizeconfig.yaml