apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - ../base
  - kube-prometheus-stack

configMapGenerator:

  - name: ingress-nginx-values
    files:
      - values.yaml=./ingress/values.yaml
    namespace: ingress-nginx

configurations:
  - kustomizeconfig.yaml