apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
resources:
  - base
  - imagepolicy.yaml
images:
  - name: 807070170018.dkr.ecr.us-east-1.amazonaws.com/moderation-api # {"$imagepolicy": "api:moderation-api-production-frankfurt:name"}
    newTag: 1.0.0-production.build.100 # {"$imagepolicy": "api:moderation-api-production-frankfurt:tag"}
replicas:
  - name: moderation-api
    count: 5
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::807070170018:role/EKSModerationApiFrankfurt
      name: moderation-api
      namespace: api
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: moderation-api
      namespace: api
    spec:
      template:
        spec:
          nodeSelector:
            type: cpu