# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-external-secrets
  namespace: aws-external-secrets
spec:
  releaseName: aws-external-secrets
  interval: 10m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: external-secrets
      version: 0.5.9
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
 