apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-api
spec:
  selector:
    matchLabels:
      app: moderation-api
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - moderation-api
                topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: moderation-api
          image: 807070170018.dkr.ecr.eu-central-1.amazonaws.com/ab3moderator
          imagePullPolicy: Always 
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "750Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      serviceAccount: moderation-api
