apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: moderation-api
  namespace: api
spec:
  image: 807070170018.dkr.ecr.eu-central-1.amazonaws.com/ab3moderator
  interval: 10s
  secretRef:
    name: ecr-credentials