apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
      version: "4.2.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 10
  timeout: 30m # default 5 minutes
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values