apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 12h
  ref:
    tag: v0.5.9
  url: http://github.com/external-secrets/external-secrets
